version: 2

updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - "ngam"

  - package-ecosystem: "docker"
    directory: ".devcontainer"
    schedule:
      interval: "monthly"
    assignees:
      - "ngam"
