repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff-check
        name: Ruff fix
        args: [--fix]
        files: '^(particula/|docs/Examples/).*\.py$'
      - id: ruff-format
        files: '^(particula/|docs/Examples/).*\.py$'
      - id: ruff-check
        name: Ruff check
        files: '^(particula/|docs/Examples/).*\.py$'
