version: '1.0'
mode: template
values:
  PACKAGE_NAME: particula
  PROJECT_NAME: adw
  REPO_URL: https://github.com/Gorkowski/particula
  REPO_OWNER: Gorkowski
  REPO_NAME: Agent
  DEFAULT_BRANCH: main
  SOURCE_DIR: adw
  TEST_DIR: adw/tests
  DOCS_DIR: docs/Agent
  TEST_COMMAND: pytest
  LINT_COMMAND: ruff check adw
  FORMAT_COMMAND: ruff format adw
  TYPE_CHECK_COMMAND: mypy adw/ --ignore-missing-imports
  ISSUE_TRACKER_URL: https://github.com/Gorkowski/Agent/issues
  TEST_FRAMEWORK: pytest
  TEST_FILE_PATTERN: '*_test.py'
  LINTER_TOOLS: ruff, mypy
  DOCSTRING_STYLE: Google
  LINE_LENGTH: '100'
  COVERAGE_THRESHOLD: '80'
  PYTHON_VERSION: '3.12'
  LICENSE_TYPE: MIT
  VERSION: 2.3.0
  LAST_UPDATED: '2025-12-14'
metadata:
  created_at: '2025-12-17T13:17:16.290592+00:00'
  created_by: adw setup env
  adw_version: 2.5.0
ignore:
  files: []
  dirs: []
  placeholders: []
