version: '1.0'
mode: live
values:
  # Package & Project
  PACKAGE_NAME: adw
  PROJECT_NAME: AI Developer Workflow
  # Directories (no trailing slashes for consistency)
  SOURCE_DIR: adw
  TEST_DIR: adw/tests
  DOCS_DIR: docs/Agent
  # Commands
  TEST_COMMAND: pytest
  LINT_COMMAND: ruff check adw
  FORMAT_COMMAND: ruff format adw
  TYPE_CHECK_COMMAND: mypy adw/ --ignore-missing-imports
  # Repository
  REPO_URL: https://github.com/Gorkowski/Agent
  REPO_NAME: Agent
  REPO_OWNER: Gorkowski
  ISSUE_TRACKER_URL: https://github.com/Gorkowski/Agent/issues
  DEFAULT_BRANCH: main
  # Tooling
  TEST_FRAMEWORK: pytest
  TEST_FILE_PATTERN: '*_test.py'
  LINTER_TOOLS: ruff, mypy
  DOCSTRING_STYLE: Google
  # Standards
  LINE_LENGTH: '100'
  COVERAGE_THRESHOLD: '80'
  PYTHON_VERSION: '3.12'
  LICENSE_TYPE: MIT
  # Metadata
  VERSION: '2.3.0'
  LAST_UPDATED: '2025-12-14'
metadata:
  created_at: '2025-12-14T12:45:16.647768'
  created_by: adw setup template init
  adw_version: 2.4.0
  updated_at: '2025-12-14'
  updated_by: template sync - reduced to 25 core keywords
