version: '1.0'
mode: live
values:
  # Package & Project
  PACKAGE_NAME: particula
  PROJECT_NAME: particula
  # Directories (no trailing slashes for consistency)
  SOURCE_DIR: particula
  TEST_DIR: particula
  DOCS_DIR: docs
  # Commands
  TEST_COMMAND: pytest
  LINT_COMMAND: ruff check particula/
  FORMAT_COMMAND: ruff format particula/
  TYPE_CHECK_COMMAND: mypy particula/ --ignore-missing-imports
  # Repository
  REPO_URL: https://github.com/uncscode/particula
  REPO_NAME: particula
  REPO_OWNER: uncscode
  ISSUE_TRACKER_URL: https://github.com/uncscode/particula/issues
  DEFAULT_BRANCH: main
  # Tooling
  TEST_FRAMEWORK: pytest
  TEST_FILE_PATTERN: '*_test.py'
  LINTER_TOOLS: ruff, mypy
  DOCSTRING_STYLE: Google
  # Standards
  LINE_LENGTH: '80'
  COVERAGE_THRESHOLD: '80'
  PYTHON_VERSION: '3.9'
  LICENSE_TYPE: MIT
  # Metadata
  VERSION: '0.2.6'
  LAST_UPDATED: '2025-12-21'
metadata:
  created_at: '2025-12-14T12:45:16.647768'
  created_by: adw setup template init
  adw_version: 2.4.0
  updated_at: '2025-12-21'
  updated_by: configured for particula repository
