name: Claude Code Review

on:
  pull_request:
    types: [opened, ready_for_review]
    # Optional: Only run on specific file changes
    # paths:
    #   - "particula/**/*.py"
    #   - "tests/**/*.py"
    #   - "pyproject.toml"
  issue_comment:
    types: [created]

jobs:
  claude-review:
    # Run on PR open/ready_for_review from same repo, or on explicit @claude review comment
    if: |
      (github.event_name == 'pull_request' &&
       github.event.pull_request.head.repo.full_name == github.repository &&
       github.event.pull_request.draft == false) ||
      (github.event_name == 'issue_comment' &&
       contains(github.event.comment.body, '@claude review') &&
       github.event.issue.pull_request)

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write

    steps:
      - name: Check for existing Claude review
        id: check-existing
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get PR number from either event type
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            PR_NUMBER=${{ github.event.pull_request.number }}
          else
            PR_NUMBER=${{ github.event.issue.number }}
          fi

          # Check if Claude has already commented (look for Claude Code Review in comments)
          EXISTING_REVIEW=$(gh pr view $PR_NUMBER --repo ${{ github.repository }} --json comments --jq '[.comments[] | select(.author.login == "github-actions[bot]" and (.body | contains("Claude Code Review")))] | length')

          # Skip if review exists and this is NOT an explicit @claude review request
          if [ "$EXISTING_REVIEW" -gt 0 ] && [ "${{ github.event_name }}" != "issue_comment" ]; then
            echo "skip=true" >> $GITHUB_OUTPUT
            echo "Claude has already reviewed this PR. Skipping to avoid duplicate reviews."
          else
            echo "skip=false" >> $GITHUB_OUTPUT
          fi

      - name: Checkout repository
        if: steps.check-existing.outputs.skip != 'true'
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Run Claude Code Review
        id: claude-review
        if: steps.check-existing.outputs.skip != 'true'
        continue-on-error: true
        uses: anthropics/claude-code-action@v1
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          prompt: |
            REPO: ${{ github.repository }}
            PR NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}

            Please review this pull request and provide feedback on:
            - Code quality and best practices
            - Potential bugs or issues
            - Performance considerations
            - Security concerns
            - Test coverage

            Use the repository's CLAUDE.md for guidance on style and conventions. Be constructive and helpful in your feedback.

            Use `gh pr comment` with your Bash tool to leave your review as a comment on the PR.

          # See https://github.com/anthropics/claude-code-action/blob/main/docs/usage.md
          # or https://docs.claude.com/en/docs/claude-code/cli-reference for available options
          claude_args: '--allowed-tools "Bash(gh issue view:*),Bash(gh search:*),Bash(gh issue list:*),Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr list:*)"'

      - name: Comment on failure
        if: failure() && steps.claude-review.outcome == 'failure'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBER=${{ github.event.pull_request.number || github.event.issue.number }}
          gh pr comment $PR_NUMBER --repo ${{ github.repository }} --body "⚠️ Claude Code review failed. Please check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."

